export const frontendDataNeeds = {
  dashboard: [
    "preferredName",
    "currentDay",
    "currentPhase",
    "currentModule",
    "checkInCompletedToday",
    "regulationStreak",
    "assessmentTrendSummary",
    "quickTools",
    "partnerStatus",
    "audiobookResume",
  ],
  profile: [
    "anonymousUserId",
    "preferredName",
    "timezone",
    "currentPhase",
    "currentModule",
    "onboardingStatus",
    "privacyPreferences",
    "notificationPreferences",
  ],
  checkIn: [
    "safetyGateStatus",
    "selectedFeelings",
    "scaleRatings",
    "optionalReflection",
    "matchedRecommendation",
    "practiceCompletion",
    "dailyCheckInHistory",
  ],
  safetyResources: [
    "resourceName",
    "resourceType",
    "phoneNumber",
    "textInstruction",
    "availabilityLabel",
    "region",
    "priority",
  ],
  recommendations: [
    "recommendationId",
    "kind",
    "title",
    "reason",
    "duration",
    "sourceModule",
    "nextRoute",
    "safetyLevel",
  ],
  chat: [
    "conversationId",
    "messages",
    "suggestedPrompts",
    "memoryUpdates",
    "sourceMode",
    "safetyFlags",
    "createdAt",
    "updatedAt",
  ],
  progress: [
    "phaseProgress",
    "moduleProgress",
    "assessmentBaselines",
    "assessmentCurrentScores",
    "streaks",
    "completedPractices",
    "reflectionCounts",
  ],
  partnerStatus: [
    "connectionState",
    "partnerDisplayInitials",
    "sharedPhase",
    "agreements",
    "inviteCode",
    "sharingPreferences",
    "soloPathStatus",
  ],
  audioProgress: [
    "trackId",
    "moduleId",
    "title",
    "durationSeconds",
    "positionSeconds",
    "completed",
    "lastPlayedAt",
  ],
  adminReports: [
    "pseudonymousUserId",
    "phase",
    "module",
    "assessmentSummary",
    "checkInSummary",
    "safetyResourceUsage",
    "contentEngagement",
    "dateRange",
  ],
} as const;

export const fatiqAlignmentNotes = [
  "Frontend expects stable anonymous/internal user IDs and should not receive PHI-heavy identifiers for AI memory.",
  "Dashboard endpoints should return summary objects; detailed journal/chat content should stay behind explicit admin permissions if ever allowed.",
  "Check-in APIs need safety gate status before returning normal recommendation flows.",
  "AI chat APIs should return safety flags separately from assistant text so UI can route crisis states cleanly.",
  "Admin reports should default to pseudonymized summaries, not raw full user journal answers.",
] as const;
